# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e804f39f53cc459a79d966af61d0115c3da64188740be56229b78ed1c974bd581f4e97a8d55230ebb49e9919f801acc47c1a7ad1213fbcd0c650049ac069c4e5

test:
  secret_key_base: c7821623fa48d6046e6524cefa5b2f53204f2f5507559a5b791c5a9990a469895aa7419a5e7feb2fd52f3cadfcf4ac3eed89a80b3b12db1d4f93464447bb6d09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
